---
title: "Disentangling technoscientific media discourses"
author: "Tabea Lüders"
format: html
toc: true
toc-location: left
bibliography: references_phd.bib
embed-resources: true
---

# Introduction {#sec-intro}

Content analyses lay at the core of communication sciences. As only original method of the field [@roessler2017, p. 15] they are especially popular within journalism and mass media communication studies [@frueh2017, p. 15] as such widespread media contents and thus their understanding are enormously important in and for societies [@dgpuk2008].

However, despite its long tradition and inherent entanglement with the development of communication sciences as such [e. g., @frueh2017, pp. 11-12; @brosius_et_al2022, pp. 143-144], there have been, still exist and newly arise several problems regarding a truly knowledge-making and therefore efficient application of the method within in the field, its subdisciplines and beyond. Roughly, these problems can be traced back to three incidential developments over more than at least 50 years of content analytic empirical social research following for example the well-known prime example of Harold D. Lasswell [-@lasswell1941]:

  1. a **wide application spectrum** [e. g., @roessler2017, p. 14; @oehmer_et_al2023a, part II to V],
  2. a tendency to generate **"atheoretical work"** [@evans_et_al1995], and
  3. a **lack of infrastructures** for collaboration, sharing and/or overview [e. g., @heft_et_al2023, pp. 356-357; @oehmer_et_al2023b].
  
While in fact the first characteristic is considered to be a strength of the method, it promotes at the same time the questionable or lacking links between empirical studies and broader theories and hampers the generation of common infrastructures. Consequently, exhausting the methods potentials, as it is currently understood and done, leads to a scattering of empirical studies which also means that the conceptualised operationalisations and the used instruments as well as the achieved findings often remain isolated or only loosely interconnected within the area. This circumstance is not only problematic in terms of efficiency but moreover inconsistent with the scientific principle or claim of cumulative knowledge production [e. g., @freese1972; @parsons1954, p. 350]. This becomes particularly obvious when various content analyses are reviewed under a more general social question than can be typically answered in singular studies. One of these overarching interests directly emerging from the self-conception of the respective research community in Germany to contribute to the explanation of the "reciprocal relationship between communication, media and society" [@dgpuk2008] is the probing question of the relationship between mass media and societal, thus, political decision-making.

In this regard, there are several theories looking at the societal role of (mass) media, such as McCombs and Shaw's [@-mccombs_et_al1972] theory of agenda-setting, the theory of medialisation [e. g., @imhof2006; @meyen2009; @neuberger2016], or the cultivation hypothesis brought forward by Gerbner [e. g., -@gerbner1969] to name a few examples. What most of them have in common is a general constructivist perspective from which mass media constructs a certain type of reality by selection and presentation [e. g., @brosius_et_al1995] and, typically pressuming a functional differentiation of modern societies [see also e. g., @gerhards1991; @schimank2001], shapes a society's shared reality [e. g., @luhmann1995, p. 5]. Furthermore, within in the community it is also (nearly) common sense that media depictions do not just affect the societal environments they are embedded in, but are similarly influenced by them as well. Most of all they depend on information from other societal systems like politics, economy or science, which they acquire through observation of and/or correspondence with representatives (individuals, organisations, institutions) of these other systems. Thus, mass media, particularly traditional journalism, is often, and also in this work, conceptualised as "autonomous observer" [@kohring1997, p. 217] of the society. This means that the contents included in media coverage are - in various degrees - simultaneously reflecting and constructing societal processes.

This bidirectional function of mass media is especially valued in democratic societies where media is also oftentimes understood as "fourth estate" [e. g., @altmeppen_et_al1998]. In this context, it is presumed that many of the media contents are reflecting (and constructing) public exchange between societal actors who are authorised with political power and other societal actors (stakeholders, audience) that (ideally) legitimise their power and the resulting decisions. This normative basis of democracies was especially described by the German sociologist Jürgen Habermas [-@habermas1990; -@habermas1998] who described this mutual negotiation of decisions that affect a whole society between actors in different positions with the term "discourse". Accordingly, media coverage that mirrors or moderates such debates can be described as "media discourse". Thus, analysing not only media content, but understanding public discourses that are reflected in the media are a central interest of many communication scientists.

Nevertheless, as previously indicated, trying to meet this research interest and provide an answer to the overarching question of characteristics of public media discourses is with respect to the current content analytical practices and the resulting scattering and incomparability of existing empirical studies nearly impossible. However, the question is to big (and dynamic) to be answered in one single study or even a whole singular research project. Therefore the here reported PhD project is not aiming at ultimately or preliminary answering this question. Rather, by focussing on the more specific subdomain of technoscientific reporting central to science communication studies as an example, it is devoted to developing a framework for a more comparable and, therefore also, efficient content analytical research on media discourses, including a theoretical basis as well as overarchingly applicable and accessible (partly automated) instruments. All phases of the project are therefore motivated by the hope of contributing to a research environment, where singular study results contribute step by step to a profound understanding of media's role in constructing and transmitting public discourses and thus, bring the community closer to find satisfying answers to one of its central questions.

To do so, this report documents the whole PhD project including its theoretical foundations and conceptualisations as well as the development of concrete operationalisations, instruments and infrastructures and their application and evaluation in several exemplary studies. Therein, three published papers and/or submitted manuscripts associated with each phase of the PhD project are knitted together in this document and enriched with further background information that could not be included (in detail) in the papers. Thus, the remaining report encompasses a total of seven chapters that are subsumed under four parts that each accompanies one phase of the whole research project. Starting from scratch, the first chapter is dealing more profoundly with the aforementioned assumptions explaining the relevance of the project. Thus, it shall provide a well-explained and empirically supported answer to the questions of why it is worth it to analyse technoscientific media coverage by means of content analysis and if and where there is room or need for improvement. For the critical and empirical discussion of the relevance-founded assumptions, results from a systematic review of the research area [@lueders2025] are mainly reported in this chapter.  A crucial second part of preparing the project was then thorough theoretical work. As this is one of the main criticism towards current research practices raised here, well-defined, comprehensible and/or justifiable conceptualisations of the central objects of research are expected to be the bar this whole project is fundamentally measured against. Thus, the second chapter aims at addressing **technoscientific media discourses** on an elaborate theoretical basis. Based on the questions of what can be described as **technoscientific** media coverage and how to define **media discourse**, an understanding of the concept encompassing four conditions which need to be fulfilled in order to analyse such technoscientific media discourses by means of content analysis is proposed. Finally, this concept is narrowed down to concrete so-called *technoscientific media discourse types* (in the following only referred to as "discourse types") by connecting theoretical considerations with empirical insights from the aformentioned review [@lueders2025]. Moving to the next phase of the project, these theoretical concepts were then operationalised in a modular way and corresponding instruments (further) developed. Focussing on the task of data collection, the development of the modular codebook by, for example, reviewing applied instruments and/or investigated characteristics in existing studies is reported and its core as well as (some) discourse-type-specific modules are introduced and explained (chapter 3). Additionally, chapter 4 is dedicated to a small excursus on automatisation, computer-/or app-based data collection and associated requirements and challenges regarding open and reproducible research as some of the core variables included in the modular codebook are/can be collected automatically and/or app-based which improves efficiency and allows for an upscaling of general/"basic", discourse-structural content analyses. The associated and (further) developed app-based and automated tools are, thus, also introduced in this chapter. Following that, the third project phase to test and evaluate the developed theoretical and methodological framework on a larger scale is presented, mainly building upon a paper/manuscript [@lueders2_sobald_vorhanden] where results from multiple explorative, thus descriptive, content analyses of various exemplary technoscientific media discourse types were comparatively summarised. Due to the operationalisation of media discourse in chapter 2, this chapter does not only include and discuss classical descriptive methods of data analysis, but also applies methods for the analysis of co-presence and clusters of interaction in media discourses which have been recently proposed by [@seeberger_et_al_sobald_vorhanden] in a paper/preprint/submitted manuscript. The goal of the last project phase was then to assess whether the proposed framework might also contribute to the detection of patterns that are stable within particular discourse types and thus, probably characteristic for them. Consequently, the second to last chapter summarises and discusses the results of multiple hypothesis-driven content analytical enquiries of technoscientific media coverage assigned to various discourse types [@lueders3_sobald_vorhanden], until the complete project and its contribution to the research area is finally critically reviewed and transferred to an outlook for future content analytical research on media discourse structures in the last concluding chapter of the presented work.

# Part I: Preparing systematic content analytical research on technoscientific media discourses {#sec-I}

The first chapter of this report takes a look at the preparation of systematic content analytical research on technoscientific media discourses. According to the ideal research process of social sciences [e. g., @frueh2017, pp. 90-95; @roessler2017, p. 38], it is, therefore, focussed on elaborating the relevance, goals and conditions - in summary, the epistemological interest - of a research project during the so-called "context of discovery"^[Translation of the German term "Entdeckungszusammenhang"] as well as the thorough reporting of the current state of research and theory building in the "context of justification"^[Translation of the German term "Begründungszusammenhang"]. Thus, in the first section of the chapter, the relevance of a common theoretical and methodological framework for content analyses on technoscientific media coverage will be explained through a systematic review of a sample of 371 existing empirical studies conducted at the beginning of the PhD project in 2025 *and published as single-author paper in Journal in Jahr*. As an expansion and reaction to this study, the second section of the chapter is devoted to answering one of the assumed and investigated explanations for the in the first part of the chapter extracted scattering of current relevant scientific publications, namely weak or lacking theoretical embeddings of empirical studies [see also @evans_et_al1995; @parsons1954, p. 350]. Accordingly, it is focused on the theoretical derivation of concept of **technoscientific media discourses** as adequate background for content analytical studies on corresponding media coverage. However, as will also be shown throughout this theory building section, the proposed theoretical framework is only one of many possibilities and not fitting for all kinds of technoscientific media coverage or questions and research interests directed at similar public mass (media) communication^[other theoretical embeddings might be for example derived from other theories in communication science, e. g., agenda-setting, medialisation, other social sciences like sociology or humanities, e. g., STS studies, (science) philosophy...].

## I.1 Epistemological relevance: Current investigation of technoscientific media coverage {#sec-I_1}

As previously mentioned, following the ideal path of social research, thoroughly considering the relevance, goals and contexts of a research project is essential before the start of the "actual" empirical research as they fundamentally define the frame in which adequate methods can be developed and results can be interpreted [@frueh2017, p. 71]. Thus, it is indispensable for the research process to have an early idea of what the scientific enquiry shall deliver, that is, which gap of knowledge shall be made smaller or closed and/or which problem(s) shall be addressed. Even though Früh [-@frueh2017, p. 71] emphasizes that scientific research does not always have to deal with "world-shaking problems"^[Translation of the original German quote: "weltbewegende Probleme"], the intended gain in knowledge should be somehow meaningful, for example, for the respective research community. Looking at the community in communication science, such meaning can be attributed to research motivated by "the essential communication issues of our time" [@sawyeroj] that are derived from an "outstanding importance of communication and media in societies"^[Translation of the original German quote: "herausragende Stellenwert, den Kommunikation und Medien in der Gesellschaft haben"] [@dgpuk2008]. However, further explaining the specific type of communication, namely journalistic media coverage^[provided no other comment, the term "media coverage" is in this report referring to professional/journalistic mass media reporting] on technology or science examined in the presented research project, and its relevance to society and/or communication science is firstly aimed at in this section. Secondly, the current state of research on the contents of this type of media coverage will be presented and problems as well as potentials of the present research practice are named. Tied together, these sub-sections justify the epistemological relevance of the PhD project to develop a framework for more comparable, potentially cumulative content analytical research on media coverage of science and technology.

### I.1.1 Why is technoscientific media coverage worthy of investigation? {#sec-I_1_1}

The question why it is relevant to examine media coverage of science and technology is strictly speaking combining two questions that need to be answered first: 1) Why is **media coverage** worthy of investigation? and 2) Why is media coverage of **science and technology** relevant?

Starting with media coverage in general, first of all a precision of the term "media coverage" as it is used throughout this report is necessary. Hence, here the term only refers to professional, that is journalistic, examinations with certain topics on mass media platforms, typically in newspapers, but other forms of mass media such as television or online media are at this stage^[in the empirical phase of the project media coverage was restricted to *traditional/textual mass media (news papers/online news papers?)*, further explanation of that decision is provided in *chapter 3*] not excluded. Thus, to explain the relevance of such media coverage, it is useful to take a look at the function of journalism in modern societies.

In this context, three keywords seem especially eye-catching in a macroscopic sense^[There are also many other keywords and theoretical considerations applied or appliable to journalim (research), a good German overview is for example provided in "Handbuch Journalismustheorien" edited by Martin Löffelholz and Liane Rothenberger [-@loeffelholz_et_al2024]]: **constructivism**, **function/service system** and **normative expectations**.

Within communication science the **constructivist basic position** that reality is not directly cognisable, but constructed through communicative processes or products (e. g., language [e. g., @weber2024], news media [e. g., @schulz1976]) is widespread [@hepp_et_al2017, p. 183]. Building on that, mass media is in various theoretical traditions conceptualised as (co-)producer of or platform to discuss and agree on societally shared and accepted reality constructions [see also @kepplinger2011]. One often-used theoretical framework based on constructivism is the sociological systems theory, in which mass media and/or journalism are described as so-called **function or service systems** of the society or public [e. g., @bloebaum2024; @kohring1997; @gerhards_et_al1990]. From that perspective, mass media is one of several systems that constitute a modern, functionally differentiated society [e. g., @luhmann1987]. Therein, functional differentiation is basically a description of collective task sharing in a macroscopic sense, which means that definable parts of a society - the function systems - are devoted to solve certain societal problems to maintain its functioning. To do so, each system has evolved an own logic of operation, the so-called function code, to reduce the complexity of societal problems through selection and enable the finding of solutions. For example, the science system deals with aspects of societal problems that focus on knowledge (or "truth"), while the economy focusses on money and the legal system on questions of justice. Thus, each system deals with different problems or - as primarily focussed here - addresses the same problem in a different manner. Consequently, each system constructs its own selective reality of a complex problem. Yet, it is never independent of its environment (the other systems), already because an adequate addressing of societal issues through task sharing requires a subsequent compilation of relevant selective solutions from various systems as parts of the solution to the whole problem, but also because the processes in one system can always have intended or unintended consequences for other systems. Accordingly, function systems need to observe their environment as well as themselves to adapt to external changes and expectations, but also to develop own expectations for their environment to maintain their functionality [see @kohring1997, pp. 243-245]. At that point, the action enabling complexity reduction through system-specific selection becomes a problem for the systems since the reality constructions and entangled results of each system are not immediately comprehensible for its environment and the systems itself do not have the structures and resources to find and translate these potentially relevant external viewpoints to accordingly react to them. Furthermore, singular systems are not able to compile external reality constructions and associated solutions for a shared/splitted problem without falling back to their own function code. However, such a "neutral" reconstruction of the complexity of a problem is necessary to find overarching societal solutions in modern democracies [e. g., @habermas1998]. Therefore, societies need not only a system that detects and collects all available, related system-specific viewpoints and solutions, but also translates and transmits this information (back) to every involved system. That is where mass media comes in and what led the influential German sociologist Niklas Luhmann [-@luhmann1995, p. 5] to his often-quoted statement: "What we know about our society [...], we know through mass media."^[Translation of the original German quote: "Was wir über unsere Gesellschaft [...] wissen, wissen wir durch die Massenmedien."]
In the existing theoretical literature it is a bit ambiguous whether journalism and/or mass media^[the terms are used interchangeably in the following] itself serves as a societal *function system* [e. g., @bloebaum2024] or whether it has to be described as a *service system* subordinated to the function system of the so-called public [@kohring1997]. Nevertheless, the differences between both approaches are not that big and thus, neglectable at this point. While for example Blöbaum [-@bloebaum2024, p. 125] describes journalism^[Not that his as well as Kohring's [-@kohring1997] descriptions focus on a specific (probably the most widespread and traditional) form of journalism, namely information or news journalism. Therefore, they are not necessarily adequate for other forms of journalism, like entertainment journalism.] as function system committed to the function code of information, Kohring [-@kohring1997, p. 252] describes a function system which he calls "the public" that applies the code of "multiple-system affiliation"^[Translation of the German term "Mehrsystemzugehörigkeit] to which journalism serves as *service system* by using the same logic of operation. Regardless of whether journalism is a function or a service system, it has evolved structures and procedures to address the previously explained societal problem of mediating between various systems and externally compiling related information from different systems. This bridging function is achieved through constant observation of the societal environment for new events and selecting and comprehensibly present only those which are informative for the society, that is events that are relevant for more systems than the one they originated from. Even though the generation of (normative) expectations itself are explicitly excluded from descriptive social theories such as systems theory, the mere description of the societal function of journalism and mass media implies the societal importance and special status of it. It is therefore not surprising that Filipović and Ulrich [-@filipovic_et_al2024, p. 302] describe journalism as "action field with a specific normativity"^[Translation of the original German quote: "Handlungsfeld mit einer spezifischen Normativität"]. Typically **normative expectations** towards journalism are tightly connected to overarching societal norms that can be derived from the political structures and principles of different states. So, comparative theories and studies on media systems [e. g., @brueggemann_et_al2014; @hallin_et_al2004; @siebert_et_al1963] have already suggested that the political contexts in which mass media is embedded influences the structures and processes of mass media leading to different types of media systems. Focussing exclusively on democratic societies, as in this report through its later main focus on media coverage in modern Germany, Strömbäck [-@stroembaeck2005] has worked out normative implications for journalism depending on the concrete model of democracy building the foundation of a society. According to him, in *procedural democracies*, which are basically societies that fulfill the minimal standards to be described as democracies, the only expectation towards citizens and politicians is to respect the democratic principles, but not to make use of them. Accordingly, the only normative implications towards journalism are respecting the democratic principles as well and acting as a watchdog to expose acts threatening these basic principles. On the contrary, in *participatory* and *deliberative democracies* journalism is expected to enable the participation of citizens in political decision-making processes by not only informing and mobilising them in a top-down manner, but also serving as a bottom-up "speaking tube" and/or platform to foster rational and equal discussions between various stakeholders, citizens and decision-makers striving for consensus [see also @habermas1998].

Taking together these considerations on the societal function of journalism, the contents of (information) journalistic mass media coverage are worthy of investigation as they can provide valuable insights in the handling of societal problems, especially pointing to the exchange of reality constructions and potential solutions between various societal systems, represented through stakeholders, and the political decision-making process. Further reflections on this connection of media coverage and democratic decision-making will be presented in @sec-I_2 focussing on the description of media coverage as discourse.

Now, after having outlined why journalistic mass media coverage is worthy of scientific investigation, in the context of this research project there is also a need for justification of focussing on a specific type of journalistic reporting, namely the coverage of science and technology. While further reflections on which aspects of science and technology (results, products, consequences, astonishment, achievements...) can become subjects of media discourse and whether they are best called "issues", "topics" or otherwise will be carried out in @sec-I_2, in this section the more general, but closely related role of science and technology in and for society is reviewed at this point to explain why science and technology focussed media coverage is an interesting and thus, valuable object of research - not only in the sciences of science communication (as will also be shown in the following results from the carried-out systematic review @sec-I_1_2).

As already mentioned in passing, science^[for better readability, without other specification the single term "science" will always include technology in the following] can be also conceptualised as a function system in modern societies according to systems theory. Its primary societal function and thus, also its self-sustaining purpose is the pursuit of truth, or (maybe less normatively loaded) knowledge. Consequently, the information generated within the science system is always generated with respect to its potential to (better) explain observed phenomena that are considered to be part of a shared, societal reality which can be better dealt with (e. g., managed or endured) the more extensive and detailed it is understood. However, as explained earlier, due to this functional differentiation, other aspects of this shared reality relevant for the system's environment (e. g., the clarification of legal or moral questions) are pragmatically excluded from sciences as the processes and methods, which were/are all developed respecting this specific function code, are not able to answer these questions^[Yet, the questions itself or the provided answers can become objects of scientific enquiry, for example in legal or political sciences]. Nevertheless, this purposeful orientation of science does not lead to a total exclusion of normativity from the system which was also heavily debated in the so-called "Werturteilsstreit" prominently featured by the German sociologist Max Weber [e. g., @weber1988]. Thus, to reach the overarching goal of approaching truth by intersubjective, standardised - colloquially probably rather described as "objective" or neutral - knowledge generation, scientific principles such as, for example, the Mertonian [-@merton1942] norms of universalism, communism, disinterestedness and organised scepticism or Karl Popper's principle of falsification (see @keuth2019, p. 54-55) have evolved and are not only used to measure scientific performances internally, but also from an external point of view. So, for example, trustworthiness of science and therefore also trust in it and its societal role (i. e., involvement in societal/political decision-making) is not only associated with competence (e. g., intelligence, skills, qualification/education, knowlege, expertise), but also benevolence (e. g., effort to improve life quality, treating others with dignity, consideration, not hurting others, responsibility), integrity (e. g., honesty, ethicality, sincerity, good character, morality, keeping promises, not misleading) and openness (e. g., well-listening, politeness, welcoming feedback, telling whole stories, respecting other views, sharing information/not withholding information) [see e. g., @cologna_et_al2025; @besley_et_al2021, p. 11-13; @hendriks_et_al2015, p. 6]. Furthermore, the scientific value of truth is also reflected in public expectations towards science as, for instance, in a recent global survey by Cologna et al. [-@cologna_et_al2025, p. 714] 75 % of the respondents "agree[d] that scientific research methods are the best way to find out whether something is true or false." In consequence, science is presented with high authority leading to exacting demands in modern societies: For once, it shall support and/or facilitate decision-making by providing "legitimate and definitive knowledge" to "push back the realm of uncertainty" [@zehr1999, p. 8-9] and secondly, it is closely associated with ideologies of innovation and (economic) growth [@lechevalier_et_al2019, p. 1]. Altogether, the high external value of science can be narrowed down to its potential to improve the quality of life - for individuals as well as entire societies.
However, this does not mean that the concrete role and configuration of science is the same and fixed around the world and at different moments in time. Instead, its desired impacts and contributions are constantly up for discussion - sometimes to a greater extent and sometimes less. Thus, the science system is not only prompting, advising or otherwise supporting societal decision-making, but subject to such decisions as well. Like previously explained with respect to journalism and mass media, at least in democratic societies, political decisions (ideally) represent common or consensual decisions by the society as a whole (or at least a majority). Hence, for the societal democratic contexts in which this report is situated, it can be assumed that political decisions concerning the science system reflect public attitudes towards it since they agglomerate as smoothly as possible various societal opinions, desires, demurs and so on to a framework that is (to various degrees) binding for the addressed systems and/or their organisational and individual members. One such framework that, therefore, represents the described optimistic, hopeful, but also demanding view of science and emphasises its currently great societal importance is the so-called Budapest Declaration of the United Nations Educational, Scientific and Cultural Organization (UNESCO) [-@unesco1999]. By accepting this declaration, the member states of the UN jointly adopt an understanding of science's contingency [@unesco1999, Annex I, p. 2] and, building on that, commit themselves to an agenda aimed at establishing "science for knowledge [and] knowledge for progress" [@unesco1999, Annex III, p. 1-3], "science for peace and development" [@unesco1999, Annex III, p. 4-9] and, probably most famous, "science in society and [...] for society" [@unesco1999, Annex III, p. 9-12]. So, nowadays at least 194 countries (member states of the UNESCO in January 2026 [@unescony]) officially claim to use scientific knowledge for the welfare of humankind, with respect to the dignity of human beings and by taking into account their responsibility towards future generations [see @unesco1999, Annex III, p. 9-10]. While with these principles the purposes and aims of science are outlined, at first glance, it remains unclear who exactly defines which goals can and should be achieved (supported) by science. Looking at this question of decisive authority / power regarding science and technology, Habermas [-@habermas1963] has described three^[for simplification the *"extended decisionist model"* is excluded as it simply reintroduces the decisionist model at points where no inherent scientific constraints alone enforce a particular decision] models of "scientificated" political decision-making [@habermas1963, p. 120-145]: While in the *"decisionist model"* decisions on science are exclusively motivated by the will of powerful politicians, this relationship between politics and science is reversed in the *"technocratic model"* where scientific discoveries and facts and/or technological developments become inherent constraints that only allow one particular decision. Nevertheless, only the third *"pragmatical model"* is, according to Habermas [-@habermas1963, p. 127] suited to describe modern democracies. In this model, there is an interdependency between science and policy, meaning that "scientific experts »advice« the decision-makers, and conversely the politicians »instruct« the scientists in terms of their practical needs"^[Translation of the original German quote: "wissenschaftliche Experten die Entscheidung fällenden Instanzen »beraten« und umgekehrt die Politiker die Wissenschaftler nach Bedürfnissen der Praxis »beauftragen«."] [@habermas1963, p. 127]. Even though some scholars like Bogner [-@bogner2021, p. 17] disagree with this conclusion by describing today's societies as "epistemocracies" and the still globally spread, competitive motto "innovate or perish" oftentimes leads to the adoption of technocratic or positivist, ideological attitudes [e. g., @oki2019], also the political decision-makers drafting the Budapest Declaration indirectly called for the implementation (or maintenance) of the pragmatical model based on a public "vigorous and informed debate on the production and use of scientific knowledge" [@unesco1999, Annex I, p. 2] including the scientific community as well as political representatives.

As this normatively desired and thus, politically tied reciprocal relationship of science in and for society simultaneously addresses multiple function systems as well as their societal environments per definition, it suggests itself that also media coverage of suiting scientific topics^[As will be shown in [@sec-I_2] not all scientific topics can be situated in this framework immediately/without further explanation] is not only interesting with respect to (personal) curiosity, but societally relevant since it represents and captures processes of societal problem-solving and decision-making on issues that are closely associated with the well-being of humankind and individual as well as collective quality of life. Through this retention of (extracts of) communicative, social processes contributing to the constitution of today's societies, interesting questions regarding the structure of these processes can be addressed through the systematic investigation of the stored materials (see also @sec-I_2). To contribute to the answer of some of these questions is the main interest of the here presented research project. Accordingly, what follows was developed with the following overarching question in mind:

  **How can structures of technoscientific media discourses be disentangled?**
  
### I.1.2 Why focussing on content analyses? {#sec-I_1_2}

Partly foreshadowing the theoretical and methodological considerations that will follow, there remains one last question regarding the relevance of the here presented research unanswered: Why is it considered to be promising to approach technoscientific media coverage by means of content analysis?

Most obviously, technoscientific media coverage as understood here is media content for which the content analytic approach nearly suggests itself even though Merten [-@merten1995, p. 14, emphasis in original] emphasises that, strictly speaking, the term "content analysis" leaves "*object*, *goal* and *type* of the analysis totally undefined"^[According to Merten for example a control of commodities in vehicles or the tasting during cooking could also be described as analyses of contents; Translation of the original German quote: "*Gegenstand*, *Ziel* und *Typik* der Analyse vollkommen undefiniert"]. However, from a perspective of communication science that builds upon models of communication and, thus, unambiguously refers to the products of this social process by the term "content", object and aim of the method are predefined. Hence, according to Merten's [-@merten1995, p. 15, emphasis in original] definition all products of communication (contents) that are somehow physically captured (manifest) are subject to the method that aims at "*investigating social reality by inferring from manifest texts to characteristics of a latent context*"^[Translation of the original German quote: "*Erhebung sozialer Wirklichkeit, bei der von Merkmalen eines manifesten Textes auf Merkmale eines nichtmanifesten Kontextes geschlossen wird.*"]. Thus, additional to describing and comparing contents as such, analysing media contents by means of content analysis allows for inferences not only to the communicators and recipients whose motivations, impressions, attitudes and so on could be also investigated more directly with other methodological approaches such as surveys, field studies etc., but also to the social contexts described in the previous section [e. g., @roessler2017, p. 27-35].

Nevertheless, despite this obviousness and its wide spread (which will also be shown in the next section [@sec-I_1_4]), content analysis is by far not the only available method to analyse media coverage. There are for example, numerous textanalytical methods in linguistics, such as functional pragmatics or narrative semiotic (for further examples, see [@titscher_et_al1998]) Furthermore, albeit sometimes controversial, various types of content analysis are typically distinguished. Most prominently quantitative (standardised) [e. g., @oehmer_et_al2023a; @riffe_et_al2019] and qualitative content analysis [e. g., @mayring1994] are opposed to each other due to their different methodological repertoires [@hildebrandt_et_al2015, p. 300]. Yet, some scholars such as Früh [-@frueh2017, p. 40; see also e. g., @schlobinski1996, p. 15-16], argue that every identification of textual contents is primarily qualitative that is just translated to countable units which is why the differentiation between quantitative and qualitative approaches is rejected and mixed-methods approaches that explicitly combine both are proposed. In this project, a similar point of view is taken, though sticking to the discrimination between quantitative and qualitative procedures. Aiming at comparing various analyses of technoscientific media coverage to identify certain structural correlations, which will also be referred to as *structural patterns* in the following, the whole research project is set out nomothetically which is a common reason for choosing more standardised - or at least standardisable - quantitative methods [@hildebrandt_et_al2015, p. 302]. However, not later than when it comes to the interpretation of these quantitative results, the "hidden qualitativity" [@schlobinski1996, p. 15] comes to the fore as alone, they are not more than specific descriptions of the analysed material. Thus, not before the results from quantitative content analyses are embedded in suitable interpretative, that are qualitative, contexts, the proclaimed inferences to broader social contexts from media coverage through content analysis can be justified. Consequently, while methodically this research is entirely located in the tradition of standardised, quantitative, manual as well as automated content analysis, its theoretical framework as well as its operationalisation is heavily inspired and influenced by proposals and insights from a specific qualitative approach, namely Discourse Analysis (DA). More precisely, Critical Discourse Analysis (CDA) that has been brought forward by Michel Foucault [@foucault2002] in his "archaeology of knowledge"-framework and its continuation in the sociology of knowledge as so-called knowledge sociological Discourse Analysis (WDA) proposed by, for example, Keller [-@keller2019], are therefore not only fundamental for working out the theoretical foundation of the project [see @sec-I_2], but also included in methodological decisions such as the development of concrete instruments (e. g., the identification of characteristics to be analysed as variables) or the selection of productive evaluation methods [**ggfs. Verweis auf Kapitel zu Auswertungsmethoden**].

Following this, the overarching question to whose answer everything that follows shall contribute is refined to:
  
  **How can structures of technoscientific media discourse be disentangled by means of content analysis?**
  
### I.1.3 Why looking at structural characteristics? {#sec-I_1_3}

Looking at the refined research question motivating the whole PhD project, there remains one last question unanswered. That is: Why are structural components of media coverage spotlighted in this project and not other, seemingly more common characteristics as regards content, like for example the prevalent enquiry of frames [e. g., @oneill_et_al2015; @matthes_et_al2008; @nguyen_et_al2024; @carver_et_al2013; @nerlich_et_al2013; @nienierza2014] or topics [e. g., @chandelier_et_al2018; @kieslich_et_al2022; @mayor_et_al2023; @keller_et_al2020]?

To understand this decision prior to explaining concretely what structures of media discourse are and which of them can be analysed in content analyses (at least in this project) [see @sec-I_2], one has again to take a step back and reconsider the overarching goal of this kind of investigation. Aiming at moving beyond just describing media coverage of technoscientific subjects^[to dodge the conceptually important distinction of issues and topics, which will be closer looked at in @sec-I_2, the term "(discourse) subject" is used henceforward to refer to both at this point] and approaching inferences to latent contexts informing as well as being carried and captured in manifest media content (see previous section [@sec-I_1_2]), specific single case studies of certain technoscientific discourses are necessary and important, but, translating a basic principle laid out in the sociological explanation of social phenomena (e. g., @coleman1990; @esser1999) to this context, not sufficient to come to more general conclusions regarding technoscientific discourses as a whole. This is mainly because such discourses are not suddenly appearing out of nowhere or triggered by a singular, initialising event, but slowly and steadily arise from the - not necessarily intended or conscious, but unavoidable, thus automatic - co-action (in this case: communication) between individual and/or collective actors below the societal macro-level. Following that, they can be described as so-called emergent (social) phenomena which are usually best explained by applying the sociological (macro-)micro-macro logic. Hence, an explanation of technoscientific discourse as emergent phenomenon is possible not before the variety of individual technoscientific discourses is somehow aggregated (see also, e. g. @esser2007).
According to Esser [-@esser2007, p. 97, emphasis in original], for such an aggregation of different individual components, there have to be established so-called "*rules of transformation*"^[Translation of the original German term "*Transformationsregeln*"] that entail "*general* and *formal* rules and deductions"^[Translation of the original German quote "*allgemeine* und *formale* Regeln und Ableitungen"] beyond case specific information. Thus, to find such bridging rules, it is necessary to temporarily blend out the - often more interesting and/or eye-catching - specifics of the individual components and focus on the - maybe, at first sight, less exciting - similarities between them. Not only regarding social phenomena, such common ground can be often found looking at basic structures. For example, in biology where there is an immensity of different life forms to be analysed in detail, looking at them conjointly, for instance, in medical research, not seldom it comes down to similar basic elements (e. g., the four basic modules of life: proteins, nucleic acids, lipids, and carbohydrates) that allow cross-boundary work, more general conclusions, and thus in most cases, greater progress. 
Yet, social phenomena, such as media coverage, are not made of molecules as biological systems and life forms are, but that does not mean that there is no comparable set of basic modules that underlies all of them. On the contrary, just like various animals can be described as conglomerates of cells, proteins or molecules, the type of informative media coverage mirroring and carrying public debates targeted in this research project can be narrowed down to similar fundamentals. Thus, in the course of this examination, this common ground is expected to be found in structural components rather than in characteristics related to contents.
From this perspective, they serve as basis for the recognition of regularities and differences over time and across multiple types of technoscientific media coverage, which can be described as **(structural) patterns** of technoscientific media discourses. Like the identification of specific arrangements of molecules that take up similar functions in various biological organisms, for example as specific enzymes, enables more targeted research questions, the formulation of hypotheses as well as expectations and predictions regarding the functions and effects of these molecules in other, not yet directly examined life forms, the identification of structural patterns in societally relevant media coverage of science and technology might also allow for more comparable, thus, general, targeted, or even prognostic investigations of such reporting [@QuelleMuster].
However, breaking down such a social phenomenon to its basic modules is an enormous reduction of complexity, which requires continuous critical consideration [@QuelleKomplexitaetsreduktion]. Therefore, this type of structural content analysis is enormously dependent on thoroughly compiled, comprehensive theoretical frameworks, especially when it comes to cumulation and aggregation of results in terms of generalisation [see, e. g., @freese1972]. Yet, more than 30 years ago, Evans and Priest [-@evans_et_al1995, p. 327] raised doubts on the fulfillment of this condition by ascribing "a partially deserved reputation of generating atheoretical work" to the long-lasting performance of content analyses in (science) communication science. To check whether this critique and the related call for better theoretically embedded content analyses is still adequate and relevant, a systematic review of the current content analytic research practice looking at the following research questions has been performed:

[RQs Review]
 
### I.1.4 How are the contents of technoscientific media coverage currently analysed? {#sec-I_1_4}

### I.1.5 Problems and potentials of the current content analytical research practice {#sec-I_1_5}

## I.2 Theoretical foundation: What are technoscientific media discourses? {#sec-I_2}
